version: "3.8"
services:
  db:
    build:
      context: ./postgresql
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: ./phpmyadmin
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"

volumes:
  local_pgdata:
  pgadmin-data: